language: java

notifications:
  email: false
  
matrix:
  include:
    - os: linux
      jdk: openjdk10

addons:
  sonarcloud:
    organization: "shawnhack-github"

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
